---
kind: pipeline
type: docker
name: default

trigger:
  event:
    exclude:
      - pull_request

steps:
  - name: setup
    image: node:22-alpine
    when:
      event: [push]
      branch:
        exclude: [build]
    volumes:
      - name: yarn_cache
        path: /tmp/cache
    commands:
      - yarn --frozen-lockfile --cache-folder /tmp/cache

  - name: build
    image: node:22-alpine
    when:
      event: [push]
    depends_on:
      - setup
    environment:
      NEXT_PUBLIC_SANITY_PROJECT_ID:
        from_secret: SANITY_PROJECT_ID
      NEXT_PUBLIC_SANITY_DATASET:
        from_secret: SANITY_DATASET
    commands:
      - yarn build

  - name: lint
    image: node:22-alpine
    when:
      event: [push]
    depends_on:
      - setup
    commands:
      - yarn lint

  - name: typecheck-sanity
    image: node:22-alpine
    when:
      event: [push]
      branch:
        exclude: [build]
    depends_on:
      - setup
    environment:
      NEXT_PUBLIC_SANITY_PROJECT_ID:
        from_secret: SANITY_PROJECT_ID
      NEXT_PUBLIC_SANITY_DATASET:
        from_secret: SANITY_DATASET
    commands:
      - apk add --no-cache git
      - yarn sanity:generate_schema
      - yarn sanity:typegen
      - git status --porcelain
      - sh -c '
        if [ -n "$(git status --porcelain)" ]; then
          echo "❌ Sanity types are outdated. Run sanity typegen generate and commit the changes.";
          git diff;
          exit 1;
        else
          echo "✅ Sanity types are up to date.";
        fi
        '

  - name: typescript
    image: node:22-alpine
    when:
      event: [push]
      branch:
        exclude: [build]
    depends_on:
      - setup
    commands:
      - yarn types

  - name: docker
    image: plugins/docker
    when:
      branch:
        - master
      event: push
      status: success
    depends_on:
      - build
      - lint
      - typecheck-sanity
      - typescript
    environment:
      NEXT_PUBLIC_SANITY_PROJECT_ID:
        from_secret: SANITY_PROJECT_ID
      NEXT_PUBLIC_SANITY_DATASET:
        from_secret: SANITY_DATASET
    settings:
      registry: https://registry.webkom.dev
      repo: registry.webkom.dev/webkom/fondet
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - version-${DRONE_COMMIT_SHA:0:7}
        - latest
      build_args_from_env:
        - NEXT_PUBLIC_SANITY_PROJECT_ID
        - NEXT_PUBLIC_SANITY_DATASET

volumes:
  - name: yarn_cache
    host:
      path: /tmp/drone-cache/yarn

---
kind: signature
hmac: 57f2aff0d1901b8fd33a99abf91bf7f0ea0d62085860fd0b962647c31890a3be

...
